<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Preserves the deterministic conversational output records generated by the AI pipelines.
 * 
 * Every node iteration writes its structural logic payload into this model
 * to build the complete timeline context window for subsequent analytical agents.
 */
class Message extends Model
{
    /**
     * Allows fully automated matrix injections across all table columns without mass-assignment exceptions.
     * 
     * @var array
     */
    protected $guarded = [];
}
