<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Stores expanded project-analysis artifacts generated by Piper.
 *
 * Records are append-only in practice and represent extraction snapshots
 * that can be replayed into epic/story generation.
 */
class PiperProjectAnalysis extends Model
{
    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'project_id',
        'source_conversation_ids',
        'recurring_themes',
        'repeated_goals',
        'phases_mentioned',
        'failure_modes_discussed',
        'technical_constraints',
        'model_routing_decisions',
        'expanded_context',
        'raw_payload',
    ];

    /**
     * Cast JSON-like columns into PHP arrays for stable API responses.
     */
    protected $casts = [
        'source_conversation_ids' => 'array',
        'recurring_themes' => 'array',
        'repeated_goals' => 'array',
        'phases_mentioned' => 'array',
        'failure_modes_discussed' => 'array',
        'technical_constraints' => 'array',
        'model_routing_decisions' => 'array',
        'raw_payload' => 'array',
    ];

    /**
     * Get the project this analysis belongs to.
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }
}
